FROM openjdk:11-jre
ARG DOKERSIZE:VERSION=V0.6.1
ARG EXPOSED_PORT=8082
ENV SPRING_PROFILES_ACTIVE docker
ADD https://github.com/jwilder/dockerize/releases/download/${DOCKERIZE_VERSION}/dockerize-alpine-linux-amd64-${DOCKERIZE_VERSION}.tar.gz dockerize.tar.gz
RUN tar -xzf dockerize.tar.gz
RUN chmod +x dockerize
ADD ./target/*.jar /app.jar # target klasoru icindeki tum jar uzantili dosyalari al app.jar olarak image icine ekle
EXPOSE ${EXPOSED_PORT}
ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"] # illa bu komutun calismasini istiyorsak CMD yerine kullaniriz. Java kodunun durmaini engelleyen kod “urandom”.